/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.PhieuLamTheDAO;
import com.edusys.entity.PhieuLamThe;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XDate;
import com.edusys.utils.XImage;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THANH VINH
 */
public class DangKyTheJDialog extends javax.swing.JDialog {
    PhieuLamTheDAO pltDAO = new PhieuLamTheDAO();
    int row = -1;
    /**
     * Creates new form DangKyTheJDialog
     */
    public DangKyTheJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGLoaiphieu = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Pan1_1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMaPLT = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtMaDG = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPhiThe = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        rdoGiaHanThe = new javax.swing.JRadioButton();
        rdoDangKyTheDocGia = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtNgayLapPhieu = new javax.swing.JTextField();
        btnDangKy = new javax.swing.JButton();
        Pan1_2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDangKyThe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - ĐĂNG KÝ THẺ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("ĐĂNG KÝ THẺ");

        Pan1_1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu làm thẻ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel21.setText("Mã phiếu làm thẻ:");

        jLabel22.setText("Mã nhân viên:");

        jLabel25.setText("Mã đọc giả:");

        jLabel27.setText("Loại phiếu:");

        jLabel28.setText("Phí thẻ:");

        txtPhiThe.setEditable(false);
        txtPhiThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhiTheActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnIn.setText("In phiếu");

        btnGLoaiphieu.add(rdoGiaHanThe);
        rdoGiaHanThe.setText("Gia hạn thẻ");
        rdoGiaHanThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGiaHanTheActionPerformed(evt);
            }
        });

        btnGLoaiphieu.add(rdoDangKyTheDocGia);
        rdoDangKyTheDocGia.setText("Đăng kí thẻ đọc giả");

        jLabel2.setText("Ngày lập phiếu:");

        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pan1_1Layout = new javax.swing.GroupLayout(Pan1_1);
        Pan1_1.setLayout(Pan1_1Layout);
        Pan1_1Layout.setHorizontalGroup(
            Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan1_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pan1_1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pan1_1Layout.createSequentialGroup()
                        .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPLT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaDG)
                            .addComponent(txtNgayLapPhieu))))
                .addGap(65, 65, 65)
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Pan1_1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhiThe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rdoDangKyTheDocGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdoGiaHanThe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(99, 99, 99))
                    .addGroup(Pan1_1Layout.createSequentialGroup()
                        .addComponent(btnPrev)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangKy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIn))))
        );
        Pan1_1Layout.setVerticalGroup(
            Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan1_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtMaPLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(rdoGiaHanThe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoDangKyTheDocGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhiThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(Pan1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnIn)
                    .addComponent(btnDangKy))
                .addGap(22, 22, 22))
        );

        Pan1_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblDangKyThe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu làm thẻ", "Loại phiếu ", "Phí thẻ", "Ngày lập phiếu "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDangKyThe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDangKyTheMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDangKyThe);

        javax.swing.GroupLayout Pan1_2Layout = new javax.swing.GroupLayout(Pan1_2);
        Pan1_2.setLayout(Pan1_2Layout);
        Pan1_2Layout.setHorizontalGroup(
            Pan1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pan1_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        Pan1_2Layout.setVerticalGroup(
            Pan1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan1_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Pan1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pan1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pan1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pan1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhiTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhiTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhiTheActionPerformed

    private void rdoGiaHanTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGiaHanTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoGiaHanTheActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        new DangKyDocGiaJDialog(null,true).setVisible(true);
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void tblDangKyTheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDangKyTheMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
           this.row = tblDangKyThe.getSelectedRow();
           this.edit();
       }
    }//GEN-LAST:event_tblDangKyTheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyTheJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyTheJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyTheJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyTheJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKyTheJDialog dialog = new DangKyTheJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pan1_1;
    private javax.swing.JPanel Pan1_2;
    private javax.swing.JButton btnDangKy;
    private javax.swing.ButtonGroup btnGLoaiphieu;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoDangKyTheDocGia;
    private javax.swing.JRadioButton rdoGiaHanThe;
    private javax.swing.JTable tblDangKyThe;
    private javax.swing.JTextField txtMaDG;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaPLT;
    private javax.swing.JTextField txtNgayLapPhieu;
    private javax.swing.JTextField txtPhiThe;
    // End of variables declaration//GEN-END:variables
    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        fillTable();
        this.row = -1;
        this.updateStatus();
    }
    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDangKyThe.getModel();
        model.setRowCount(0); // xoá tất cả các hàng trên Jtable
        try {
            List<PhieuLamThe> list = pltDAO.selectAll();
            for(PhieuLamThe plt : list){
                Object[] row = {
                    plt.getMaplt(),
                    plt.getManv(),
                    plt.getLoaiphieu()?"Gia hạn thẻ" :"Đăng ký thẻ đọc giả",
                    plt.getPhithe(),
                    plt.getNgaylapphieu()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void updateStatus() {
        boolean edit = (this.row >=0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblDangKyThe.getRowCount() - 1);
        
        // Trạng thái form
       txtMaNV.setEditable(!edit);
       btnThem.setEnabled(!edit);
       btnSua.setEnabled(edit);
       btnXoa.setEnabled(edit);
       
       //Trạng thái điều hướng
       btnPrev.setEnabled(edit && !first);
       btnNext.setEnabled(edit && !last);
    }
    
    void setForm(PhieuLamThe plt){
        txtMaPLT.setText(plt.getMaplt());
        txtMaNV.setText(plt.getManv());
        rdoGiaHanThe.setSelected(plt.getLoaiphieu());
        rdoDangKyTheDocGia.setSelected(!plt.getLoaiphieu());
        txtPhiThe.setText(String.valueOf(plt.getPhithe()));
        txtNgayLapPhieu.setText(XDate.toString(plt.getNgaylapphieu(), "yyyy/MM/dd"));
    }
    
    PhieuLamThe getForm(){
        PhieuLamThe plt = new PhieuLamThe();
        plt.setMaplt(txtMaPLT.getText());
        plt.setManv(txtMaNV.getText());
        plt.setLoaiphieu(rdoGiaHanThe.isSelected());
        plt.setPhithe(Float.parseFloat(txtPhiThe.getText()));
        plt.setNgaylapphieu(XDate.toDate(txtNgayLapPhieu.getText(), "yyyy/MM/dd"));
        return plt;
    }
    
    void clearForm(){
        PhieuLamThe plt = new PhieuLamThe();
        this.setForm(plt);
        this.row = -1;
        this.updateStatus();
    }
    
    void edit(){
        String maplt = (String)tblDangKyThe.getValueAt(this.row, 0);
        PhieuLamThe plt = pltDAO.selectById(maplt);
        this.setForm(plt);
        this.updateStatus();
    }
    
    void insert(){
        PhieuLamThe plt = getForm();
            try {
                pltDAO.insert(plt);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Thêm mới thất bại");
            }
    }
  
    void update(){
        PhieuLamThe plt = getForm();
            try {
                pltDAO.update(plt);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Cập nhập thành công!");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Cập nhập thất bại");
            }
    }
    
    void delete(){
        String maplt = txtMaPLT.getText();
            try {
                pltDAO.delete(maplt);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xoá thành công");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Xoá thất bại");
            }
    }
    
    void next(){
        if(this.row < tblDangKyThe.getRowCount() -1){
            this.row++;
            this.edit();
        }
    }
    
    void prev(){
        if(this.row > 0){
            this.row--;
            this.edit();
        }
    }
  
}
